worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    # Khai báo vùng cache tên là "backend_cache"
    proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=backend_cache:10m max_size=100m inactive=60m use_temp_path=off;

    upstream user_v1 {
        server user_service:8001;
    }

    upstream user_v2 {
        server user_service_v2:8001;
    }

    upstream product_api {
        server product_service:8002;
    }

    upstream order_api {
        server order_service:8003;
    }

    split_clients "${remote_addr}" $user_backend {
        10%     user_v2;
        *       user_v1;
    }

    server {
        listen 80;
        server_name ru.myapi.local;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api/users/ {
            rewrite ^/api/users(/.*)$ $1 break;
            proxy_pass http://$user_backend;
        }

        location /api/product/ {
            rewrite ^/api/product(/.*)$ $1 break;
            proxy_pass http://product_api;

            # # Cache config
            # proxy_cache backend_cache;
            # # proxy_cache_valid 200 302 10m;
            # proxy_cache_valid 404 1m;
            # add_header X-Cache-Status $upstream_cache_status;
        }

        location /api/order/ {
            rewrite ^/api/order(/.*)$ $1 break;
            proxy_pass http://order_api;

            # # Cache config
            # proxy_cache backend_cache;
            # proxy_cache_valid 200 302 5m;
            # proxy_cache_valid 404 1m;
            # add_header X-Cache-Status $upstream_cache_status;
        }
    }
}
