FROM python:3.10-slim

WORKDIR /app
COPY . .
RUN pip install psycopg2-binary pika httpx prometheus-client  aio_pika

# CMD ["python", "main.py"]

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]

